spring:
  application:
    name: bankingMsBFF
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    pool:
      max-size: 5
      initial-size: 2
  profiles:
    active: ${DEPLOY:prod}

server:
  port: 11103

secret_keys:
  codes:
    jwt: ${JWT_SECRET}
    crypt_key: ${CRYPT_KEY}

